### ISSUE TITLE
Watermark

### ISSUE THREAD

**Issue by timbrookers** [bataak/dict-mn#1]
Сайн байна уу

Юуны түрүүнд таны хөгжүүлж байгаа төсөлд амжилт хүсье. Маш хэрэгтэй зүйл.
Алдаа шалгагч өнөөгийн нөхцөлд ЗАЙЛШГҮЙ болчихлоо. Зөв бичдэг хүн гэж ер нь байхгүй боллоо.
Бид энэхүү алдаа шалгагчийг өөрийн сайтын нийтлэлийн алдааг шалгах хэрэгслэл болгон ашиглахыг хүсч байна. Ингэхдээ нийтлэл бүрийн дор "Зөв бичигдэв" гэсэн тамга байршуулах боломж байгаа эсэхийг тодруулах гэсэн юм.

Хүндэтгэсэн

Батням

**Comment by bataak** [comment]
Сайн байна уу,

Хэрэглэгч болсон явдалд баярлалаа. Энэ бүрэн боломжтой. Амжилт хүсье!

Батаак

**Comment by timbrookers** [comment]
Сайн байна уу

Тамга хэрхэн оруулах вэ?

Хүндэтгэсэн

Батням

**Comment by bataak** [comment]
Одоогоор лого байхгүй тул текст хэлбэрээр оруулахад болно гэж бодож байна. Жишээлбэл:

`<div title="Монгол үгийн алдаа шалгах толь https://zuv.bichig.dev">Зөв бичигдэв</div>`

гэж оруулж болно. Гэхдээ өөрсдийнхөөрөө оруулсан ч болно, хамаагүй-чөлөөтэй.
