### ISSUE TITLE
suffix

### ISSUE THREAD

**Issue by aramis-it** [bataak/dict-mn#2]
Энэ ямар дүрмээр хаанаас гарч ирсэн хувирлууд вэ?
-тайтай 
-тайтайг
-тайтайгаа
-тайтайгаар
-тайтайгаараа
-тайтайгаас
-тайтайгаасаа
-тайтайд
-тайтайдаа
-тайтайн
-тайтайнх
-тайтайнхыг

**Comment by bataak** [comment]
Hi,

Нэр үгээс үүссэн тэмдэг нэрийн хувирал. Жишээ нь, номтой/номгүй хүмүүс гэдгийг тодотгож, номтой нь (номтойчууд), номтойтой нь, эсвэл номгүйтэй нь гэх мэт. Хэрэглээ нь хязгаарлагдмал хэдий ч хуучны сонгодог зохиолуудад (Нацагдорж, Дамдинсүрэн, Ринчен нарын) дээрхтэй төстэй хэллэг тохиолдоно.

**Comment by ulziibadrakh-p** [comment]
харин хүмүүсээс асуусан ийм хувирлууд байхгүй гэхээр жоохон гайхаад
