### ISSUE TITLE
help

### ISSUE THREAD

**Issue by aramis-it** [bataak/dict-mn#3]
-лөгсөддөдөө
ийм төгсгөлтэй үг олсонгүй жишээ тайлбар хийгээд өгөөч

**Comment by bataak** [comment]
Яг ямар учир зорилготой, юу хийхийн тулд асууж байгааг тодруулмаар байна. Дээрх нөхцөл буруу хувилсан байна. -лөгсдөдөө гэх нь зөв.

**Comment by aramis-it** [comment]
hunspell ашиглах гээд яг толь ашиглаад үгнүүд үүсгэхээр хэтэрхий том бааз үүсэж байна. Nspell дээр санах ой халиад байх шиг таг алга болчих юм. Тэгээд яг ямар хувирлууд үүсээд байгааг мэдэх санаатай

**Comment by bataak** [comment]
2 тэрбум үг үүснэ hunspell default function алдаатай үүсгэнэ. Санах ой хүрэхгүй байх магадлалтай. Ямар хувирал үүсгэж байгааг мэдэх зорилго нь юу вэ? Уг нь Affix файл дээрээ тодорхой байгаа.

**Comment by aramis-it** [comment]
Хувирлууд зөв үүсэж байгаа эсэхийг мэдэх санаатай.

**Comment by bataak** [comment]
Эргэлзэж байгаа үгүүд байгаа юм уу, жишээлэн үзүүлбэл.
