### ISSUE TITLE
morphology analysis дээр ямар нөхцлөөр хувирсан үг болохыг нь хэрхэн мэдэх вэ?

### ISSUE THREAD

**Issue by bayartsogt-ya** [bataak/dict-mn#4]
Сайн байна уу @bataak,

Энэхүү ажлыг цагаа гарган бүтээсэнд баярлалаа.

2 асуулт байна.

Асуулт 1:
Доорх жишээ нь дээр эмнэлгээс гэсэн үгийг `ээс` гэсэн нөхцлөөр хувирлаа гэдгийг `fl:E3` гэдгээс хэрхэн мэдэх вэ?
```bash
╰─$ hunspell -d mn_MN -m
эмнэлгээс
эмнэлгээс  st:эмнэлэг fl:E3
```

`mn_MN.aff`-с `E3`-г хайж үзэхэд
```
 7710 SFX E3 Y 53
 7711 SFX E3 0 /0708 .
 7712 SFX E3 0 т/03 [вг]
 7713 SFX E3 0 эд/03 [^эийүе]с
 7714 SFX E3 0 т/03 [эийүе]с
 7715 SFX E3 иг гийг/03 иг
 7716 SFX E3 иг гийн иг
 7717 SFX E3 иг гийнх/070873 иг
 7718 SFX E3 иг гийнхэрхүү/070873 иг
 7719 SFX E3 иг гээ иг 
 7720 SFX E3 иг гээр/03 иг
 7721 SFX E3 иг гэрхүү/070873 иг
 7722 SFX E3 иг гээс/03 иг
 7723 SFX E3 ис сийг/03 ис
 7724 SFX E3 ис сийн ис 
 7725 SFX E3 ис сийнх/070873 ис
 7726 SFX E3 ис сийнхэрхүү/070873 ис
 7727 SFX E3 ис сээ ис 
 7728 SFX E3 ис сээр/03 ис
 7729 SFX E3 ис сэрхүү/070873 ис
 7730 SFX E3 ис сээс/03 ис
 7731 SFX E3 эв вийг/03 эв
 7732 SFX E3 эв вийн эв
 7733 SFX E3 эв вийнх/070873 эв
 7734 SFX E3 эв вийнхэрхүү/070873 эв
 7735 SFX E3 эв вээ эв
 7736 SFX E3 эв вээр/03 эв
 7737 SFX E3 эв вэрхүү/070873 эв
 7738 SFX E3 эв вээс/03 эв
 7739 SFX E3 эг гийг/03 эг
 7740 SFX E3 эг гийн эг
 7741 SFX E3 эг гийнх/070873 эг
 7742 SFX E3 эг гийнхэрхүү/070873 эг
 7743 SFX E3 эг гээ эг 
 7744 SFX E3 эг гээр/03 эг
 7745 SFX E3 эг гэрхүү/070873 эг
 7746 SFX E3 эг гээс/03 эг
 7747 SFX E3 эс сийг/03 эс
 7748 SFX E3 эс сийн эс
 7749 SFX E3 эс сийнх/070873 эс
 7750 SFX E3 эс сийнхэрхүү/070873 эс
 7751 SFX E3 эс сээ эс
 7752 SFX E3 эс сээр/03 эс
 7753 SFX E3 эс сэрхүү/070873 эс
 7754 SFX E3 эс сээс/03 эс
 7755 SFX E3 0 нд/03 [ийеэү]
 7756 SFX E3 0 ний [ийеэү]
 7757 SFX E3 0 нийх/070873 [ийеэү]
 7758 SFX E3 0 нийхэрхүү/070873 [ийеэү]
 7759 SFX E3 0 г/03 [ийеэү]
 7760 SFX E3 0 нээс/03 [ийеэү]
 7761 SFX E3 0 гээр/03 [ийеэү]
 7762 SFX E3 0 гэрхүү/070873 [ийеэү]
 7763 SFX E3 0 н [ийеэү]
```

Асуулт 2:
Задаргаанаас хувирсан үгийг гаргаж ирэх contract байгаа болов уу?
Жишээ нь:
```
input: st:эмнэлэг fl:E3
output: эмнэлгээс
```

**Comment by bataak** [comment]
Баярлалаа. Эхний асуултын хувьд энэхүү толио хангалттай хэмжээнд хөгжүүлсний дараа нөхцөл бүрийн утгыг оруулахаар төлөвлөсөн байгаа. Хоёр дахь асуултын хувьд гэвэл яг юунд ямар зорилгоор ашиглах хэрэгтэй болоод дээрх асуудал хөндөгдөж байгааг мэдмээр байна.

**Comment by bayartsogt-ya** [comment]
> Эхний асуултын хувьд энэхүү толио хангалттай хэмжээнд хөгжүүлсний дараа нөхцөл бүрийн утгыг оруулахаар төлөвлөсөн байгаа.

Хөгжүүлэлт идэвхитэй хийгдэхгүй байгаа гэж ойлгосон юм, тэгвэл цаашдаа хөгжүүлэлт хийгдэж сайжирснаас ямар учраас ийн хувиргалт үүссэнийг мэдэх боломжтой юм байна гэж ойлголоо.


> Хоёр дахь асуултын хувьд гэвэл яг юунд ямар зорилгоор ашиглах хэрэгтэй болоод дээрх асуудал хөндөгдөж байгааг мэдмээр байна.

Монгол хэл дээр хөгжүүлэгдэж байгаа language model-үүд үгээ задлахдаа одоогоор дандаа statistic pair tokenizer үүд ашиглаад байгаа юм байна гэж бодоод, энэ чиглэлд илүү тухайн хэлний дүрмийг (жишээ нь morphological analysis) тусгасан үг задлагч байвал language modeling task нь өөрөө хялбар болох юм байна гэсэн үүднээс судалж байгаа юм.

Энэ санаа мөн [Хуягбаатар багш](https://github.com/kbatsuren)-ийн хийсэн ажлуудаас inspired болсон гэж бодож байна.

Би жишээ болгоод huggingface дээр байгаа tokenizer-үүдийг харьцуулсан [demo](https://huggingface.co/spaces/bayartsogt/real-time-tokenizer) хийсэн юм.

Одоогийн байгаа learning framework үүд дотор tokenizer ихэвчлэн 2 function-г time complexity багатайгаар хийж чадаж байгаа нь `tokenizer.encode()` ба `tokenizer.decode()` функцууд ба тэр нь сургалтын явцад үр дүнгээ evaluate хийхэд чухал үүрэгтэй бас санагдаж байгаа юм.

Энэ чиглэлд таны ажил болон МУИС-ийн lemmatize хийдэг демо одоогоор туршсан ч `decode` functionality дутмаг хэвээр байгаа санагдаад асуусан юм.

**Comment by bataak** [comment]
Hunspell дээр монгол толь хөгжүүлэх онолын ажил анх 10-аад жилийн тэртээ хийгдсэн байсан бөгөөд сүүлийн 3 жилийн хугацаанд бодитоор хэрэгжин хөгжүүлэгдэж байгаа юм. Hunspell толийг NLP тал дээр stemming хийхэд ашиглаж болно. Чиний асуусан сүүлийн асуултад хариу болгож unmunch (https://github.com/hunspell/hunspell#other-executables) ашиглаж үзэж болох юм гэж бодогдож байна. twofold affix stripping ашигласан толинуудад энэ нь ажилладаггүй тул unmunch-г засаж таарна.

NLP салбарт судалгаа хийдэг шинэ залуу эрдэмтэн багш нарын бүтээлүүдийг цаг зав гаргаж байгаад сонирхох болно. Баярлалаа.

**Comment by bayartsogt-ya** [comment]
Хариу өгсөнд баярлалаа, энэ issue-г хаалаа.
