### ISSUE TITLE
"эрсдэл"

### ISSUE THREAD

**Issue by FiableDotBiz** [bataak/dict-mn#5]
**Is your feature request related to a problem? Please describe.**
The word "эрсдэл" is lacking.
https://mongoltoli.mn/dictionary/detail/137004

**Describe the solution you'd like**
I suggest to add "эрсдэл" in the list of roots.

**Comment by bataak** [comment]
Саналаа илгээсэнд баярлалаа. Монгол толь, журамласан толинууд маш их алдаатай бичигдсэн байгаа. Монгол үсгийн дараах дүрмийн дагуу -д биш -т бичигдэнэ:
1. [https://zuv.bichig.dev/core.html#-41](https://zuv.bichig.dev/core.html#-41)
2. [https://zuv.bichig.dev/book.html](https://zuv.bichig.dev/book.html) (369-р тал)

Дээрх асуудал алдаа биш тул хэлэлцүүлгийг хааж байна.

**Comment by FiableDotBiz** [comment]
Хурдан хариулсанд баярлалаа.

1) Хэл бол дүрэм биш харин ёс заншил. Дүрмийг ёс заншлын дагуу зохиодог. "үг" гэдэг үгээс "үгүүлэх" биш "өгүүлэх" гэж бичдэг болсон нь жаахан сонин харин танай тольд "өгүүлэх" байгаа, "үгүүлэх" байхгүй. "цэцэг" гэдэг үг нь 2 олон тоотой: "цэцгүүд" ба "цэцэгс" бөгөөд хоёулаа таны тольд байгаа. "багш нарын өрөө" харин "багшийн дээд сургууль" гэдэг (Яагаад "багш нарын дээд сургууль" биш бол?) "байгууллах" гэдэг үйл үг байхгүй мөртлөө "байгууллага" гэж байдаг. Г.м. "эрсдэл site:mn" гэж Google-оор хайвал 1 280 000 хариу гардаг. Үүнээс "эрсдэл site:legalinfo.mn" гэж хайвал 1 240 хариу гардаг (Жишээлбэл Иргэний хуулиас "247 дугаар зүйл. Үр шим болон эрсдэл худалдан авагчид шилжих" ба Эрүүгийн хуулиас: "4.5 дугаар зүйл. Үндэслэл бүхий эрсдэл" ). Харин "эрстэл site:mn" гэж хайвал зөвхөн 10 хариу гардаг. Дуртай ч дургүй ч "эрсдэл" бол Монголчууд, Монгол Улсын Их хурал, Монгол Улсын шүүгчид, Монгол Улсын Шинжлэх ухааны академи г.мэтийн ашигладаг үг. Үүнийг монгол үг гэдэг.

2) "эрсдэл" гэдэг нь таны дурдсан 18-р дүрмийг зөрчөөгүй: "р" бол заримдаг гийгүүлэгч биш, "с", "д" бол заримдаг гийгүүлэгч бөгөөд хоёр дахь заримдаг гийгүүлэгч буюу "д" үсгийн дараа эгшиг орсон.
Таны дурдсан 41-р дүрмийг зөрчөөгүй гэж би бодож байна. "эрс" бол нэр үг биш, харин тэмдэг нэр. Миний мэдлэг бага харин "эрс" гэдгийг нэр үгээр ашигласныг би хэзээ ч үзээгүй байх ("эр" гэдгийн олон тооны утгаас гадна).

**Comment by bataak** [comment]
Энд хэлийг шинжлэх ухааны талаас ярьж байгаа тул дүрэм зайлшгүй яригдана. Жишээлбэл, байгууллага гэдэг үгийн хувьд байгуул гэсэн үйл үндэс дээр -лага хэмээх дагавар залгаж байна. Бас үгүүлэх  гэх нь зөв гэлээ. Яагаад буруу вэ гэвэл, үг гэдэг нь нэр үг, нэр үгэнд -үүл/уул гэсэн үйл үгийн дагавар залгагдахгүй.

Эрсдэл гэдэг үгийн хувьд Монгол үсгийн дүрмийг зохиогч толь бичигтээ "эрст" гэж оруулсан байна. Эрстэх гэсэн үйл үгэнд -л дагавар залгаад эрстэл хэмээх нэр үг үүсэж байна. Эрс тэс гэсэн хэллэг байдаг энд тэмдэг нэрийн үүргээр орсон байна.

Бичсэнээс чинь, өөрийг чинь монгол хэлний мэдлэг дунд сургуулийн төвшнөөс доор байна гэж дүгнэхээр байна. Монголд өнөөдөр эх хэлээ маруухан мэддэг хүмүүс олширсон тул  үгийн зөв бичлэгийг хайлтын системээс гаргаж дүгнэх нь өнгөц үйлдэл гэж бодож байна.
